# Generated by Django 3.2.8 on 2021-11-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Create',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(max_length=122)),
                ('author', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=200)),
                ('date', models.DateField()),
            ],
        ),
    ]
